<datalist id="searchlist">
    <option value="Насос-форсунка топливная цилиндра"></option>
    <option value="Ресивер воздушный"></option>
    <option value="Поршень-гильза комплект"></option>
    <option value="Водяной насос с муфтой"></option>
    <option value="Насос водяной с прокладкой"></option>
    <option value="Тормозной шланг переднего моста"></option>
    <option value="Трос открывания"></option>
    <option value="Втулка шатуна верхняя"></option>
    <option value="Кольцо гильзы"></option>
    <option value="Прокладка блока цилиндров"></option>
    <option value="Комплект щеток стеклоочистителя"></option>
    <option value="Комплект сцепления"></option>
    <option value="Датчик уровня топлива в баке"></option>
    <option value="Цапфа задней полуоси"></option>
    <option value="Кронштейн стабилизатора"></option>
    <option value="Гайка шестигранная"></option>
    <option value="Напорный трубопровод турбины"></option>
    <option value="Усилитель привода сцепления"></option>
    <option value="Фильтр топливный"></option>
    <option value="Радиатор охлаждения"></option>
    <option value="Панель кабины боковая левая"></option>
    <option value="Прокладка выпускного коллектора"></option>
    <option value="Кольцо уплотнительное"></option>
    <option value="Втулка распредвала"></option>
    <option value="Сальник ступицы"></option>
    <option value="Фиттинг ГБЦ"></option>
    <option value="Трубка топливная"></option>
    <option value="Вискомуфта вентилятора"></option>
    <option value="Втулка распредвала с буртиком"></option>
    <option value="Насос ГУР"></option>
    <option value="Прокладка"></option>
    <option value="Фильтр масляный"></option>
    <option value="Комплект топливных фильтров"></option>
    <option value="Фиттинг электропроводки"></option>
    <option value="Блок переключения передач"></option>
    <option value="Уплотнение"></option>
    <option value="Уплотнение масляного насоса"></option>
    <option value="Щетки стеклоочистителя"></option>
    <option value="Клапан обратный"></option>
    <option value="Рычаг стеклоочистителя"></option>
    <option value="Стартер"></option>
    <option value="Вилка блокировки"></option>
    <option value="Генератор"></option>
    <option value="Трубка"></option>
    <option value="Прокладка коллектора"></option>
    <option value="Втулка стабилизатора"></option>
    <option value="Вязкостная муфта"></option>
    <option value="Подушка передняя кабины"></option>
    <option value="Блок подготовки воздуха"></option>
    <option value="Термостат охлаждения двигателя"></option>
</datalist>